Marks= []
f1= int(input("Enter marks here: "))
Marks.append(f1)
f2= int(input("Enter marks here: "))
Marks.append(f2)
f3= int(input("Enter marks here: "))
Marks.append(f3)
f4= int(input("Enter marks here: "))
Marks.append(f4)
Marks.sort()
print(Marks)
print(sum(Marks))