fruit= []
f1= input("Enter Fruits name: ")
fruit.append(f1)
f2= input("Enter Fruits name: ")
fruit.append(f2)
f3= input("Enter Fruits name: ")
fruit.append(f3)
f4= input("Enter Fruits name: ")
fruit.append(f4)
print(fruit)