s= set()
n = input("Enter numbber 1: ")
s.add(int(n))
n = input("Enter numbber 1: ")
s.add(int(n))
n = input("Enter numbber 1: ")
s.add(int(n))
n = input("Enter numbber 1: ")
s.add(int(n))
n = input("Enter numbber 1: ")
s.add(int(n))
n = input("Enter numbber 1: ")
s.add(int(n))
n = input("Enter numbber 1: ")
s.add(int(n))
n = input("Enter numbber 1: ")
s.add(int(n))
n = input("Enter numbber 1: ")
s.add(int(n))

print(s)